language: node_js
node_js:
  - "8"
before_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
  - npm install
script:
  - npm test
after_script:
  - codeclimate < d3/test/coverage/lcov.info
